// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: Smart_Gadget
#include "../../../../../audio/audio_aio.h"
#include "ui_MusicPlayer.h"
LV_IMG_DECLARE(ui_music_pattern_png);    // assets/pattern.png
LV_IMG_DECLARE(ui_music_play_png);    // assets/play.png
LV_IMG_DECLARE(ui_music_album_png);    // assets/album.png
LV_IMG_DECLARE(ui_music_backward_png);    // assets/backward.png
LV_IMG_DECLARE(ui_music_forward_png);    // assets/forward.png
LV_IMG_DECLARE(ui_music_pause_png); 
//////////////////////////////////////
extern k_bool    g_enable_audio_codec2;
static uint32_t active_index_sound = 0;
static lv_style_t style_radio;
static lv_style_t style_radio_chk;
static void radiobutton_init()
{
    lv_style_init(&style_radio);
    lv_style_set_radius(&style_radio, LV_RADIUS_CIRCLE);

    lv_style_init(&style_radio_chk);
    lv_style_set_bg_img_src(&style_radio_chk, NULL);

}
static void radiobutton_create(lv_obj_t * parent, const char * txt)
{
    lv_obj_t * obj = lv_checkbox_create(parent);
    lv_checkbox_set_text(obj, txt);
    lv_obj_add_flag(obj, LV_OBJ_FLAG_EVENT_BUBBLE);
    lv_obj_add_style(obj, &style_radio, LV_PART_INDICATOR);
    lv_obj_add_style(obj, &style_radio_chk, LV_PART_INDICATOR | LV_STATE_CHECKED);
}

static void radio_event_handler(lv_event_t * e)
{
    uint32_t * active_id = lv_event_get_user_data(e);
    lv_obj_t * cont = lv_event_get_current_target(e);
    lv_obj_t * act_cb = lv_event_get_target(e);
    lv_obj_t * old_cb = lv_obj_get_child(cont, *active_id);

    /*Do nothing if the container was clicked*/
    if(act_cb == cont) return;

    lv_obj_clear_state(old_cb, LV_STATE_CHECKED);   /*Uncheck the previous radio button*/
    lv_obj_add_state(act_cb, LV_STATE_CHECKED);     /*Uncheck the current radio button*/

    *active_id = lv_obj_get_index(act_cb);

    printf("Selected radio buttons: %d, %d\n", *active_id, (int)active_index_sound);  //0 1
    if(*active_id==0)//earphone
    {
    g_enable_audio_codec2=K_TRUE;
    }
    else//speaker
    {   
    g_enable_audio_codec2=K_FALSE; //
    }  
}


/////////////////////////////////////
int flag_music_state=0;
void ui_event_MusicPlayer(lv_event_t * e)
{
 if(flag_music_state==0)
  {
   audio_ao_play();
   lv_img_set_src(ui_SmartGadgetMusicPlayer_Image_Play, &ui_music_pause_png);
   flag_music_state=1;
   }
   else
   {
   audio_ao_pause();
   lv_img_set_src(ui_SmartGadgetMusicPlayer_Image_Play, &ui_music_play_png);
   flag_music_state=0; 
   }
}
void music_play_stop()
{
  if(flag_music_state!=0)
   {
   audio_ao_pause();
   flag_music_state=0; 
   }
}
void ui_MusicPlayer_screen_init(void)
{
    ui_SmartGadgetMusicPlayer_Small_label_Music_Title = lv_label_create(lv_scr_act());
    lv_obj_set_x(ui_SmartGadgetMusicPlayer_Small_label_Music_Title, 0);
    lv_obj_set_y(ui_SmartGadgetMusicPlayer_Small_label_Music_Title, 0);
    lv_obj_set_align(ui_SmartGadgetMusicPlayer_Small_label_Music_Title, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SmartGadgetMusicPlayer_Small_label_Music_Title, "appointment");
    lv_obj_set_style_text_color(ui_SmartGadgetMusicPlayer_Small_label_Music_Title, lv_color_hex(0x000746),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SmartGadgetMusicPlayer_Small_label_Music_Title, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SmartGadgetMusicPlayer_Small_label_Author = lv_label_create(lv_scr_act());
    lv_obj_set_x(ui_SmartGadgetMusicPlayer_Small_label_Author, 0);
    lv_obj_set_y(ui_SmartGadgetMusicPlayer_Small_label_Author, 25);
    lv_obj_set_align(ui_SmartGadgetMusicPlayer_Small_label_Author, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SmartGadgetMusicPlayer_Small_label_Author, "zhou hui");
    lv_obj_set_style_text_color(ui_SmartGadgetMusicPlayer_Small_label_Author, lv_color_hex(0x9C9CD9),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SmartGadgetMusicPlayer_Small_label_Author, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    
    
    ui_SmartGadgetMusicPlayer_Panel_Play_btn = lv_obj_create(lv_scr_act());
    lv_obj_set_width(ui_SmartGadgetMusicPlayer_Panel_Play_btn, 60);
    lv_obj_set_height(ui_SmartGadgetMusicPlayer_Panel_Play_btn, 60);
    lv_obj_set_x(ui_SmartGadgetMusicPlayer_Panel_Play_btn, 0);
    lv_obj_set_y(ui_SmartGadgetMusicPlayer_Panel_Play_btn, -42);
    lv_obj_set_align(ui_SmartGadgetMusicPlayer_Panel_Play_btn, LV_ALIGN_BOTTOM_MID);
    lv_obj_clear_flag(ui_SmartGadgetMusicPlayer_Panel_Play_btn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_SmartGadgetMusicPlayer_Panel_Play_btn, 60, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SmartGadgetMusicPlayer_Panel_Play_btn, lv_color_hex(0x293062),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SmartGadgetMusicPlayer_Panel_Play_btn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_SmartGadgetMusicPlayer_Panel_Play_btn, lv_color_hex(0x293062),
                                  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_SmartGadgetMusicPlayer_Panel_Play_btn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_SmartGadgetMusicPlayer_Panel_Play_btn, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_SmartGadgetMusicPlayer_Panel_Play_btn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_SmartGadgetMusicPlayer_Panel_Play_btn, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_SmartGadgetMusicPlayer_Panel_Play_btn, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SmartGadgetMusicPlayer_Panel_Play_btn, lv_color_hex(0x515EB5),
                              LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_SmartGadgetMusicPlayer_Panel_Play_btn, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_SmartGadgetMusicPlayer_Image_Play = lv_img_create(ui_SmartGadgetMusicPlayer_Panel_Play_btn);
    lv_img_set_src(ui_SmartGadgetMusicPlayer_Image_Play, &ui_music_play_png);
    lv_obj_set_width(ui_SmartGadgetMusicPlayer_Image_Play, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SmartGadgetMusicPlayer_Image_Play, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SmartGadgetMusicPlayer_Image_Play, 2);
    lv_obj_set_y(ui_SmartGadgetMusicPlayer_Image_Play, 0);
    lv_obj_set_align(ui_SmartGadgetMusicPlayer_Image_Play, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SmartGadgetMusicPlayer_Image_Play, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_SmartGadgetMusicPlayer_Image_Play, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SmartGadgetMusicPlayer_Image_Album = lv_img_create(lv_scr_act());
    lv_img_set_src(ui_SmartGadgetMusicPlayer_Image_Album, &ui_music_album_png);
    lv_obj_set_width(ui_SmartGadgetMusicPlayer_Image_Album, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SmartGadgetMusicPlayer_Image_Album, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SmartGadgetMusicPlayer_Image_Album, 0);
    lv_obj_set_y(ui_SmartGadgetMusicPlayer_Image_Album, 20);
    lv_obj_set_align(ui_SmartGadgetMusicPlayer_Image_Album, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_SmartGadgetMusicPlayer_Image_Album, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_SmartGadgetMusicPlayer_Image_Album, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_SmartGadgetMusicPlayer_Image_Album, 300, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_SmartGadgetMusicPlayer_Image_Album, lv_color_hex(0xD5D2D5),
                                  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_SmartGadgetMusicPlayer_Image_Album, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_SmartGadgetMusicPlayer_Image_Album, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_SmartGadgetMusicPlayer_Image_Album, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_SmartGadgetMusicPlayer_Image_Album, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_SmartGadgetMusicPlayer_Image_Album, 6, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SmartGadgetMusicPlayer_Image_Backward = lv_img_create(lv_scr_act());
    lv_img_set_src(ui_SmartGadgetMusicPlayer_Image_Backward, &ui_music_backward_png);
    lv_obj_set_width(ui_SmartGadgetMusicPlayer_Image_Backward, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SmartGadgetMusicPlayer_Image_Backward, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SmartGadgetMusicPlayer_Image_Backward, 30);
    lv_obj_set_y(ui_SmartGadgetMusicPlayer_Image_Backward, -60);
    lv_obj_set_align(ui_SmartGadgetMusicPlayer_Image_Backward, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_SmartGadgetMusicPlayer_Image_Backward,
                    LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_SmartGadgetMusicPlayer_Image_Backward, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_img_recolor(ui_SmartGadgetMusicPlayer_Image_Backward, lv_color_hex(0x293062),
                                 LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_SmartGadgetMusicPlayer_Image_Backward, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor(ui_SmartGadgetMusicPlayer_Image_Backward, lv_color_hex(0x515EB5),
                                 LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_img_recolor_opa(ui_SmartGadgetMusicPlayer_Image_Backward, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_SmartGadgetMusicPlayer_Image_Forward = lv_img_create(lv_scr_act());
    lv_img_set_src(ui_SmartGadgetMusicPlayer_Image_Forward, &ui_music_forward_png);
    lv_obj_set_width(ui_SmartGadgetMusicPlayer_Image_Forward, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SmartGadgetMusicPlayer_Image_Forward, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SmartGadgetMusicPlayer_Image_Forward, -30);
    lv_obj_set_y(ui_SmartGadgetMusicPlayer_Image_Forward, -60);
     lv_obj_set_align(ui_SmartGadgetMusicPlayer_Image_Forward, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_add_flag(ui_SmartGadgetMusicPlayer_Image_Forward, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_SmartGadgetMusicPlayer_Image_Forward, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_img_recolor(ui_SmartGadgetMusicPlayer_Image_Forward, lv_color_hex(0x293062),
                                 LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_SmartGadgetMusicPlayer_Image_Forward, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor(ui_SmartGadgetMusicPlayer_Image_Forward, lv_color_hex(0x515EB5),
                                 LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_img_recolor_opa(ui_SmartGadgetMusicPlayer_Image_Forward, 255, LV_PART_MAIN | LV_STATE_PRESSED);
   

    lv_obj_add_event_cb(ui_SmartGadgetMusicPlayer_Panel_Play_btn, ui_event_MusicPlayer, LV_EVENT_CLICKED, NULL);
    
    radiobutton_init();
    lv_obj_t * cont_sound_device = lv_obj_create(lv_scr_act());
    lv_obj_set_flex_flow(cont_sound_device, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_size(cont_sound_device, lv_pct(30), lv_pct(10));
    lv_obj_set_x(cont_sound_device, lv_pct(70));
    lv_obj_add_event_cb(cont_sound_device, radio_event_handler, LV_EVENT_CLICKED, &active_index_sound);
    radiobutton_create(cont_sound_device, "earphone");
    radiobutton_create(cont_sound_device, "speaker");

    /*Make the first checkbox checked*/
    lv_obj_add_state(lv_obj_get_child(cont_sound_device, 0), LV_STATE_CHECKED);
    
    
    
    
    
    
    
    
    

}
