// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: Smart_Gadget

#ifndef _UI_MUSIC_PLAYER_H
#define _UI_MUSIC_PLAYER_H
// esp-brookesia: changed
#include "lvgl.h"
#include "esp_brookesia.h"
#ifdef __cplusplus
extern "C" {
#endif



// esp-brookesia: changed
//#include "components/ui_comp.h"
//#include "components/ui_comp_hook.h"

//void upanim_Animation(lv_obj_t * TargetObject, int delay);
//void scrolldot_Animation(lv_obj_t * TargetObject, int delay);

// SCREEN: ui_SmartGadgetMusicPlayer
void music_play_stop();
void ui_MusicPlayer_screen_init(void);
void ui_event_MusicPlayer(lv_event_t * e);
extern lv_obj_t * ui_SmartGadgetMusicPlayer;
extern lv_obj_t * ui_SmartGadgetMusicPlayer_Small_label_Music_Title;
extern lv_obj_t * ui_SmartGadgetMusicPlayer_Small_label_Author;
extern lv_obj_t * ui_SmartGadgetMusicPlayer_Panel_Play_btn;
extern lv_obj_t * ui_SmartGadgetMusicPlayer_Image_Play;
extern lv_obj_t * ui_SmartGadgetMusicPlayer_Image_Album;
extern lv_obj_t * ui_SmartGadgetMusicPlayer_Image_Backward;
extern lv_obj_t * ui_SmartGadgetMusicPlayer_Image_Forward;
//extern lv_obj_t * ui_SmartGadgetMusicPlayer_Scrolldots_Scrolldots3;








#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
